apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vuecrud
  labels:
    app: vuecrud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vuecrud
        version: v1
    spec:
      containers:
      - name: vuecrud
        image: vuecrud:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
