apiVersion: v1
kind: Service
metadata:
  name: vuecrud
  labels:
    app: vuecrud
spec:
  ports:
  #port and targetport should be different
  - port: 8080
    name: port0
  selector:
    app: vuecrud
  type: NodePort
  sessionAffinity: None